### ISSUE TITLE
Groups check

### ISSUE THREAD

**Issue by kenhufford** [kenhufford/Beatup#3]
Check groups https://beatupp.herokuapp.com/#/

**Comment by helenyueyu** [comment]
- **Comment**: When I try to leave the group where I am the only member, no error is thrown - I just get redirected to a blank page. In addition, when I navigate to the main page, the group that I created (but attempted to delete) still exists, but when I click on it it directs to a blank page. 
- **Comment**: Cannot delete a group that I created.
